name = "stable-sprint-api"
main = "src/index.ts"
compatibility_date = "2024-05-14"
compatibility_flags = ["nodejs_compat"]

[vars]
VITE_CHAIN_ID = "42220"
VITE_SCORE_REGISTRY_ADDRESS = "0xc4c59f5D3a9dedE1203fFfe4e31841d88F61BDB5"

[[kv_namespaces]]
binding = "SESSIONS"
id = "e3046d5d21f04b8abfbbc329eeda1c7e"

[[d1_databases]]
binding = "DB"
database_name = "celo-arcade-db"
database_id = "04a8ae6f-e91f-4c14-840d-de8dc74ce0fb"
